from docx import Document
from docx.shared import Pt, Inches, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from pptx import Presentation
from pptx.util import Inches as PptxInches, Pt as PptxPt
from pptx.enum.text import PP_ALIGN, PP_PARAGRAPH_ALIGNMENT
from pptx.dml.color import RGBColor as PptxRGBColor
from pptx.enum.shapes import MSO_SHAPE
from io import BytesIO
from typing import List
from app.models import Project, Section
from datetime import datetime
import re

class DocumentService:
    @staticmethod
    def create_docx(project: Project, sections: List[Section]) -> BytesIO:
        doc = Document()
        
        # Set document margins
        section = doc.sections[0]
        section.top_margin = Inches(1)
        section.bottom_margin = Inches(1)
        section.left_margin = Inches(1)
        section.right_margin = Inches(1)
        
        # Add title with styling
        title = doc.add_heading(project.title, 0)
        title_run = title.runs[0]
        title_run.font.color.rgb = RGBColor(31, 78, 121)
        title_run.font.size = Pt(28)
        title_run.bold = True
        title.alignment = WD_ALIGN_PARAGRAPH.CENTER
        
        # Add topic/subtitle
        topic_para = doc.add_paragraph()
        topic_run = topic_para.add_run(project.main_topic)
        topic_run.font.size = Pt(14)
        topic_run.font.color.rgb = RGBColor(89, 89, 89)
        topic_run.italic = True
        topic_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
        
        # Add date
        date_para = doc.add_paragraph()
        date_run = date_para.add_run(f"Generated on {datetime.now().strftime('%B %d, %Y')}")
        date_run.font.size = Pt(10)
        date_run.font.color.rgb = RGBColor(128, 128, 128)
        date_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
        
        doc.add_paragraph('_' * 80)
        doc.add_paragraph()
        
        # Add sections with professional formatting
        for idx, section in enumerate(sorted(sections, key=lambda x: x.order), 1):
            heading = doc.add_heading(f"{idx}. {section.title}", level=1)
            heading_run = heading.runs[0]
            heading_run.font.color.rgb = RGBColor(31, 78, 121)
            heading_run.font.size = Pt(18)
            
            if section.content:
                paragraphs = section.content.split('\n\n')
                for para_text in paragraphs:
                    if para_text.strip():
                        if para_text.strip().startswith(('•', '-', '*')):
                            lines = para_text.split('\n')
                            for line in lines:
                                if line.strip():
                                    clean_line = line.strip().lstrip('•-* ').strip()
                                    p = doc.add_paragraph(clean_line, style='List Bullet')
                                    p.paragraph_format.left_indent = Inches(0.5)
                                    p.paragraph_format.space_after = Pt(6)
                        else:
                            p = doc.add_paragraph(para_text.strip())
                            p.paragraph_format.space_after = Pt(12)
                            p.paragraph_format.line_spacing = 1.15
                            for run in p.runs:
                                run.font.size = Pt(11)
                                run.font.name = 'Calibri'
            
            doc.add_paragraph()
        
        # Add footer
        footer_section = doc.sections[0]
        footer = footer_section.footer
        footer_para = footer.paragraphs[0]
        footer_para.text = f"Generated by DocuGen AI | {project.title}"
        footer_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
        footer_run = footer_para.runs[0]
        footer_run.font.size = Pt(9)
        footer_run.font.color.rgb = RGBColor(128, 128, 128)
        
        buffer = BytesIO()
        doc.save(buffer)
        buffer.seek(0)
        return buffer

    
    @staticmethod
    def _parse_content_structure(content: str) -> dict:
        """Parse content to determine best slide layout"""
        lines = [line.strip() for line in content.split('\n') if line.strip()]
        
        # Count different content types
        bullet_points = [l for l in lines if l.startswith(('•', '-', '*', '1.', '2.', '3.'))]
        has_numbers = any(char.isdigit() for line in content for char in line if '%' in line or '$' in line)
        
        return {
            'bullet_points': bullet_points[:6],  # Max 6 bullets
            'has_data': has_numbers,
            'line_count': len(lines),
            'needs_image': len(bullet_points) <= 3  # If few bullets, add image
        }
    
    @staticmethod
    def _add_slide_background(slide, color_scheme='blue'):
        """Add professional gradient background"""
        background = slide.background
        fill = background.fill
        fill.gradient()
        fill.gradient_angle = 90.0
        
        if color_scheme == 'blue':
            fill.gradient_stops[0].color.rgb = PptxRGBColor(31, 78, 121)
            fill.gradient_stops[1].color.rgb = PptxRGBColor(41, 98, 151)
        elif color_scheme == 'accent':
            fill.gradient_stops[0].color.rgb = PptxRGBColor(59, 130, 246)
            fill.gradient_stops[1].color.rgb = PptxRGBColor(147, 51, 234)
    
    @staticmethod
    def _add_decorative_shape(slide, position='top-right'):
        """Add decorative geometric shapes"""
        if position == 'top-right':
            shape = slide.shapes.add_shape(
                MSO_SHAPE.ROUNDED_RECTANGLE,
                PptxInches(8), PptxInches(0.5),
                PptxInches(1.5), PptxInches(1.5)
            )
        else:
            shape = slide.shapes.add_shape(
                MSO_SHAPE.ROUNDED_RECTANGLE,
                PptxInches(0.5), PptxInches(6),
                PptxInches(1.5), PptxInches(1.5)
            )
        
        shape.fill.solid()
        shape.fill.fore_color.rgb = PptxRGBColor(59, 130, 246)
        shape.fill.transparency = 0.7
        shape.line.fill.background()

    
    @staticmethod
    def create_pptx(project: Project, sections: List[Section]) -> BytesIO:
        prs = Presentation()
        prs.slide_width = PptxInches(10)
        prs.slide_height = PptxInches(7.5)
        
        # ===== TITLE SLIDE =====
        title_slide_layout = prs.slide_layouts[6]  # Blank layout for custom design
        slide = prs.slides.add_slide(title_slide_layout)
        
        # Gradient background
        DocumentService._add_slide_background(slide, 'blue')
        
        # Decorative shapes
        shape1 = slide.shapes.add_shape(
            MSO_SHAPE.ROUNDED_RECTANGLE,
            PptxInches(8), PptxInches(0),
            PptxInches(2), PptxInches(2)
        )
        shape1.fill.solid()
        shape1.fill.fore_color.rgb = PptxRGBColor(59, 130, 246)
        shape1.fill.transparency = 0.3
        shape1.line.fill.background()
        shape1.rotation = 45
        
        # Title
        title_box = slide.shapes.add_textbox(
            PptxInches(1), PptxInches(2.5),
            PptxInches(8), PptxInches(1.5)
        )
        title_frame = title_box.text_frame
        title_frame.word_wrap = True
        title_para = title_frame.paragraphs[0]
        title_para.text = project.title
        title_para.font.size = PptxPt(54)
        title_para.font.bold = True
        title_para.font.color.rgb = PptxRGBColor(255, 255, 255)
        title_para.alignment = PP_ALIGN.CENTER
        
        # Subtitle
        subtitle_box = slide.shapes.add_textbox(
            PptxInches(1), PptxInches(4.2),
            PptxInches(8), PptxInches(1)
        )
        subtitle_frame = subtitle_box.text_frame
        subtitle_para = subtitle_frame.paragraphs[0]
        subtitle_para.text = project.main_topic
        subtitle_para.font.size = PptxPt(28)
        subtitle_para.font.color.rgb = PptxRGBColor(220, 220, 220)
        subtitle_para.alignment = PP_ALIGN.CENTER
        
        # Date
        date_box = slide.shapes.add_textbox(
            PptxInches(1), PptxInches(6.5),
            PptxInches(8), PptxInches(0.5)
        )
        date_frame = date_box.text_frame
        date_para = date_frame.paragraphs[0]
        date_para.text = datetime.now().strftime('%B %d, %Y')
        date_para.font.size = PptxPt(18)
        date_para.font.color.rgb = PptxRGBColor(200, 200, 200)
        date_para.alignment = PP_ALIGN.CENTER

        
        # ===== CONTENT SLIDES =====
        for idx, section in enumerate(sorted(sections, key=lambda x: x.order), 1):
            # Use blank layout for full customization
            slide = prs.slides.add_slide(prs.slide_layouts[6])
            
            # White background with subtle gradient
            background = slide.background
            fill = background.fill
            fill.solid()
            fill.fore_color.rgb = PptxRGBColor(255, 255, 255)
            
            # Top accent bar
            accent_bar = slide.shapes.add_shape(
                MSO_SHAPE.RECTANGLE,
                PptxInches(0), PptxInches(0),
                PptxInches(10), PptxInches(0.15)
            )
            accent_bar.fill.solid()
            accent_bar.fill.fore_color.rgb = PptxRGBColor(59, 130, 246)
            accent_bar.line.fill.background()
            
            # Slide number badge
            num_circle = slide.shapes.add_shape(
                MSO_SHAPE.OVAL,
                PptxInches(9.2), PptxInches(0.3),
                PptxInches(0.6), PptxInches(0.6)
            )
            num_circle.fill.solid()
            num_circle.fill.fore_color.rgb = PptxRGBColor(59, 130, 246)
            num_circle.line.fill.background()
            
            num_text = num_circle.text_frame
            num_para = num_text.paragraphs[0]
            num_para.text = str(idx)
            num_para.font.size = PptxPt(16)
            num_para.font.bold = True
            num_para.font.color.rgb = PptxRGBColor(255, 255, 255)
            num_para.alignment = PP_ALIGN.CENTER
            
            # Title with underline accent
            title_box = slide.shapes.add_textbox(
                PptxInches(0.8), PptxInches(0.8),
                PptxInches(8), PptxInches(0.8)
            )
            title_frame = title_box.text_frame
            title_para = title_frame.paragraphs[0]
            title_para.text = section.title
            title_para.font.size = PptxPt(36)
            title_para.font.bold = True
            title_para.font.color.rgb = PptxRGBColor(31, 78, 121)
            
            # Title underline
            underline = slide.shapes.add_shape(
                MSO_SHAPE.RECTANGLE,
                PptxInches(0.8), PptxInches(1.65),
                PptxInches(2), PptxInches(0.08)
            )
            underline.fill.solid()
            underline.fill.fore_color.rgb = PptxRGBColor(59, 130, 246)
            underline.line.fill.background()
            
            # Parse content structure
            content_info = DocumentService._parse_content_structure(section.content)

            
            # Determine layout based on content
            if content_info['needs_image'] and len(content_info['bullet_points']) <= 3:
                # TWO-COLUMN LAYOUT: Content + Image Placeholder
                
                # Left column - Content
                content_box = slide.shapes.add_textbox(
                    PptxInches(0.8), PptxInches(2.2),
                    PptxInches(4.5), PptxInches(4.5)
                )
                text_frame = content_box.text_frame
                text_frame.word_wrap = True
                
                for i, bullet in enumerate(content_info['bullet_points']):
                    clean_bullet = bullet.lstrip('•-*123456789. ').strip()
                    
                    if i == 0:
                        p = text_frame.paragraphs[0]
                    else:
                        p = text_frame.add_paragraph()
                    
                    p.text = clean_bullet
                    p.level = 0
                    p.font.size = PptxPt(20)
                    p.font.color.rgb = PptxRGBColor(64, 64, 64)
                    p.space_before = PptxPt(16)
                    p.space_after = PptxPt(16)
                    p.line_spacing = 1.3
                
                # Right column - Image Placeholder
                img_placeholder = slide.shapes.add_shape(
                    MSO_SHAPE.ROUNDED_RECTANGLE,
                    PptxInches(5.5), PptxInches(2.2),
                    PptxInches(3.8), PptxInches(4.5)
                )
                img_placeholder.fill.solid()
                img_placeholder.fill.fore_color.rgb = PptxRGBColor(240, 245, 250)
                img_placeholder.line.color.rgb = PptxRGBColor(200, 210, 220)
                img_placeholder.line.width = PptxPt(2)
                
                # Icon in placeholder
                icon_text = img_placeholder.text_frame
                icon_para = icon_text.paragraphs[0]
                icon_para.text = "📊\n\nImage\nPlaceholder"
                icon_para.font.size = PptxPt(24)
                icon_para.font.color.rgb = PptxRGBColor(150, 160, 170)
                icon_para.alignment = PP_ALIGN.CENTER
                icon_text.vertical_anchor = 2  # Middle
            
            else:
                # SINGLE COLUMN LAYOUT: Full-width content
                content_box = slide.shapes.add_textbox(
                    PptxInches(0.8), PptxInches(2.2),
                    PptxInches(8.4), PptxInches(4.5)
                )
                text_frame = content_box.text_frame
                text_frame.word_wrap = True
                
                for i, bullet in enumerate(content_info['bullet_points']):
                    clean_bullet = bullet.lstrip('•-*123456789. ').strip()
                    
                    if i == 0:
                        p = text_frame.paragraphs[0]
                    else:
                        p = text_frame.add_paragraph()
                    
                    p.text = clean_bullet
                    p.level = 0
                    p.font.size = PptxPt(22)
                    p.font.color.rgb = PptxRGBColor(64, 64, 64)
                    p.space_before = PptxPt(18)
                    p.space_after = PptxPt(18)
                    p.line_spacing = 1.3
                    
                    # Add bullet styling
                    p.font.bold = False
            
            # Footer line
            footer_line = slide.shapes.add_shape(
                MSO_SHAPE.RECTANGLE,
                PptxInches(0.8), PptxInches(7),
                PptxInches(8.4), PptxInches(0.02)
            )
            footer_line.fill.solid()
            footer_line.fill.fore_color.rgb = PptxRGBColor(220, 220, 220)
            footer_line.line.fill.background()
            
            # Footer text
            footer_box = slide.shapes.add_textbox(
                PptxInches(0.8), PptxInches(7.1),
                PptxInches(7), PptxInches(0.3)
            )
            footer_frame = footer_box.text_frame
            footer_para = footer_frame.paragraphs[0]
            footer_para.text = project.title
            footer_para.font.size = PptxPt(11)
            footer_para.font.color.rgb = PptxRGBColor(150, 150, 150)

        
        # ===== THANK YOU SLIDE =====
        end_slide = prs.slides.add_slide(prs.slide_layouts[6])
        
        # Gradient background
        DocumentService._add_slide_background(end_slide, 'accent')
        
        # Decorative circle
        circle = end_slide.shapes.add_shape(
            MSO_SHAPE.OVAL,
            PptxInches(3.5), PptxInches(2),
            PptxInches(3), PptxInches(3)
        )
        circle.fill.solid()
        circle.fill.fore_color.rgb = PptxRGBColor(255, 255, 255)
        circle.fill.transparency = 0.1
        circle.line.fill.background()
        
        # Thank you text
        thank_you_box = end_slide.shapes.add_textbox(
            PptxInches(1), PptxInches(3),
            PptxInches(8), PptxInches(1.5)
        )
        thank_you_frame = thank_you_box.text_frame
        thank_you_para = thank_you_frame.paragraphs[0]
        thank_you_para.text = "Thank You"
        thank_you_para.font.size = PptxPt(64)
        thank_you_para.font.bold = True
        thank_you_para.font.color.rgb = PptxRGBColor(255, 255, 255)
        thank_you_para.alignment = PP_ALIGN.CENTER
        
        # Subtitle
        subtitle_box = end_slide.shapes.add_textbox(
            PptxInches(1), PptxInches(4.8),
            PptxInches(8), PptxInches(0.8)
        )
        subtitle_frame = subtitle_box.text_frame
        subtitle_para = subtitle_frame.paragraphs[0]
        subtitle_para.text = "Questions?"
        subtitle_para.font.size = PptxPt(32)
        subtitle_para.font.color.rgb = PptxRGBColor(220, 220, 220)
        subtitle_para.alignment = PP_ALIGN.CENTER
        
        # Footer
        footer_box = end_slide.shapes.add_textbox(
            PptxInches(1), PptxInches(6.8),
            PptxInches(8), PptxInches(0.5)
        )
        footer_frame = footer_box.text_frame
        footer_para = footer_frame.paragraphs[0]
        footer_para.text = "Generated by DocuGen AI"
        footer_para.font.size = PptxPt(16)
        footer_para.font.color.rgb = PptxRGBColor(200, 200, 200)
        footer_para.alignment = PP_ALIGN.CENTER
        
        buffer = BytesIO()
        prs.save(buffer)
        buffer.seek(0)
        return buffer

document_service = DocumentService()
